import { run as runPlainObject } from './samples/plain-object.js';
import { run as runArrayTopLevel } from './samples/array-top-level.js';
import { run as runNull } from './samples/null.js';
import { run as runDate } from './samples/date.js';
import { run as runRegExp } from './samples/regexp.js';
import { run as runMap } from './samples/map.js';
import { run as runSet } from './samples/set.js';
import { run as runArrayBuffer } from './samples/arraybuffer.js';
import { run as runSharedArrayBuffer } from './samples/shared-array-buffer.js';
import { run as runDataView } from './samples/dataview.js';
import { run as runTypedArrayInt16 } from './samples/typedarray-int16.js';
import { run as runError } from './samples/error.js';
import { run as runNodeBuffer } from './samples/node-buffer.js';
import { run as runPromise } from './samples/promise.js';
import { run as runURL } from './samples/url.js';
import { run as runURLSearchParams } from './samples/urlsearchparams.js';
import { run as runFunctionAsIs } from './samples/function-as-is.js';
import { run as runMirrorLockState } from './samples/mirror-lock-state.js';
import { run as runWeakCollections } from './samples/weakmap-weakset.js';
import { run as runClassInstance } from './samples/class-instance.js';
import { run as runSymbolsNonEnums } from './samples/symbols-non-enumerables.js';
import { run as runCircularRefs } from './samples/circular-refs.js';

console.log('@@@\n\n\n\n\n');
runPlainObject();
runArrayTopLevel();
runNull();
runDate();
runRegExp();
runMap();
runSet();
runArrayBuffer();
runSharedArrayBuffer();
runDataView();
runTypedArrayInt16();
runError();
runNodeBuffer();
runPromise();
runURL();
runURLSearchParams();
runFunctionAsIs();
runMirrorLockState();
runWeakCollections();
runClassInstance();
runSymbolsNonEnums();
runCircularRefs();
console.log('\n\n\n\n\n\n\n\n\n\n@@@');
