import { run as runExample } from './samples/example.js';
import { run as runPrimitives } from './samples/primitives-special-cases.js';
import { run as runArrays } from './samples/arrays.js';
import { run as runPlainObjects } from './samples/plain-objects.js';
import { run as runDate } from './samples/date.js';
import { run as runRegExp } from './samples/regexp.js';
import { run as runMap } from './samples/map.js';
import { run as runSet } from './samples/set.js';
import { run as runBuffers } from './samples/buffers.js';
import { run as runDataView } from './samples/dataview.js';
import { run as runTypedArrays } from './samples/typedarrays-and-buffer.js';
import { run as runError } from './samples/error.js';
import { run as runWrappers } from './samples/wrapper-objects.js';
import { run as runUrlAndParams } from './samples/url-and-searchparams.js';
import { run as runBlobFile } from './samples/blob-file.js';
import { run as runFetchApis } from './samples/fetch-apis.js';
import { run as runIntl } from './samples/intl.js';
import { run as runWeakRef } from './samples/weakref.js';
import { run as runDomNodes } from './samples/dom-nodes.js';
import { run as runWeakCollections } from './samples/weakmap-weakset-promise.js';
import { run as runCircular } from './samples/circular-references.js';
import { run as runSymbolsNonEnums } from './samples/symbols-and-nonenumerables.js';
import { run as runGettersSetters } from './samples/getters-setters.js';
import { run as runSparse } from './samples/sparse-arrays-and-holes.js';
import { run as runNegZero } from './samples/negzero-vs-zero.js';
import { run as runFnProps } from './samples/function-properties.js';
import { run as runClasses } from './samples/class-instances-and-prototypes.js';
import { run as runTypedViews } from './samples/typedarray-views.js';
import { run as runMapSetEdgeKeys } from './samples/map-set-edge-keys.js';
import { run as runHeadersCasing } from './samples/headers-casing.js';
import { run as runDomTextFragments } from './samples/dom-text-and-fragments.js';

console.log('@@@\n\n\n\n\n');

runExample();
runPrimitives();
runArrays();
runPlainObjects();
runDate();
runRegExp();
runMap();
runSet();
runBuffers();
runDataView();
runTypedArrays();
runError();
runWrappers();
runUrlAndParams();
runBlobFile();
runFetchApis();
runIntl();
runWeakRef();
runDomNodes();
runWeakCollections();
runCircular();
runSymbolsNonEnums();
runGettersSetters();
runSparse();
runNegZero();
runFnProps();
runClasses();
runTypedViews();
runMapSetEdgeKeys();
runHeadersCasing();
runDomTextFragments();

console.log('\n\n\n\n\n\n\n\n\n\n@@@');
